# Generated by Django 4.2.6 on 2023-12-08 13:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accountdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=1000)),
                ('phone', models.BigIntegerField()),
                ('acc', models.BigIntegerField()),
            ],
        ),
    ]
